fragment PageParts on Page {
  __typename
  about {
    __typename
    title
    subtitle
    backgroundImage
  }
  hero {
    __typename
    title
    description
    images {
      __typename
      src
      alt
    }
  }
  vision {
    __typename
    label
    title
    description
    image
  }
  creator {
    __typename
    name
    title
    bio
    image
  }
}

fragment PostParts on Post {
  __typename
  title
  excerpt
  coverImage
  date
  body
}
